# Generated by Django 6.0 on 2025-12-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('subzona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('grado_eclesiastico', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('Curso de Abril 2026', 'Curso de Abril 2026')], default='Curso de Abril 2026', max_length=100)),
                ('pago', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('periodo_pago', models.CharField(blank=True, choices=[('', 'Seleccione'), ('Primer periodo|1500', '07 Ene - 21 Feb | $1,500'), ('Segundo periodo|1700', '22 Feb - 31 Mar | $1,700'), ('Tercer periodo|1900', '31 Mar - 26 Abr | $1,900')], max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
