# Generated by Django 6.0 on 2026-01-02 17:39

import django.db.models.deletion
import miepi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('subzona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('grado_eclesiastico', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('Curso de Abril 2026', 'Curso de Abril 2026')], default='Curso de Abril 2026', max_length=100)),
                ('pago', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('periodo_pago', models.CharField(blank=True, choices=[('', 'Seleccione'), ('Primer periodo|1500', '07 Ene - 21 Feb | $1,500'), ('Segundo periodo|1700', '22 Feb - 31 Mar | $1,700'), ('Tercer periodo|1900', '31 Mar - 26 Abr | $1,900')], max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('subzona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('grado', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=miepi.models.qr_upload_path)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=True)),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miepi.inscrito')),
            ],
            options={
                'unique_together': {('inscrito', 'fecha')},
            },
        ),
    ]
