# Generated by Django 6.0 on 2026-01-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='denominacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='otra_denominacion',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='subzona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
