# Generated by Django 6.0 on 2026-01-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0002_inscrito_denominacion_inscrito_otra_denominacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=10),
        ),
    ]
