# Generated by Django 6.0 on 2026-01-01 21:50

import miepi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0002_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('subzona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('grado', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=miepi.models.qr_upload_path)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
