# Generated by Django 6.0 on 2026-01-01 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0003_inscrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miepi.inscrito')),
            ],
            options={
                'unique_together': {('inscrito', 'fecha')},
            },
        ),
    ]
