# Generated by Django 6.0 on 2026-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0004_alter_inscrito_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=10),
        ),
    ]
