# Generated by Django 6.0 on 2026-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0004_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
