# Generated by Django 6.0 on 2026-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0005_alter_inscrito_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='grado',
            field=models.CharField(choices=[('MINISTRO', 'MINISTRO / DIACONISA'), ('EG_ITE_ESC', 'EGRESADO DEL I.T.E. (Sistema Escolarizado)'), ('EG_ITE_AB', 'EGRESADO DEL I.T.E. (Sistema Abierto)'), ('EST_1_ESC', 'ESTUDIANTE (PRIMER AÑO) S.E.'), ('EST_2_ESC', 'ESTUDIANTE (SEGUNDO AÑO) S.E.'), ('EST_3_ESC', 'ESTUDIANTE (TERCER AÑO) S.E.'), ('EST_1_AB', 'ESTUDIANTE (PRIMER AÑO) S. ABIERTO'), ('EST_2_AB', 'ESTUDIANTE (SEGUNDO AÑO) S. ABIERTO'), ('EST_3_AB', 'ESTUDIANTE (TERCER AÑO) S. ABIERTO'), ('EST_4_AB', 'ESTUDIANTE (CUARTO AÑO) S. ABIERTO'), ('OBRERO', 'OBRERO LAICO'), ('ANCIANO', 'ANCIANO DE IGLESIA'), ('OTRO', 'OTRO (ESPECIFICAR)'), ('REP_ZONA', 'REPRESENTANTE DE ZONA'), ('REP_SUBZONA', 'REPRESENTANTE DE SUB ZONA'), ('EG_XAL_ESC', 'EGRESADO ITE CAMPUS XALAPA S. ESCOLARIZADO'), ('EG_XAL_AB', 'EGRESADO ITE CAMPUS XALAPA S. ABIERTO'), ('EG_SUR_ESC', 'EGRESADO ITE CAMPUS SURESTE S. ESCOLARIZADO'), ('EG_ELGIN', 'EGRESADO ITE CAMPUS ELGIN, IL'), ('SIN_RANGO', 'SIN RANGO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='zona',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'CENTRAL'), ('CDMX', 'CD. DE MEX.'), ('PUEBLA', 'PUEBLA, PUE.'), ('XALAPA', 'XALAPA, VER.'), ('MISANTLA', 'MISANTLA, VER.'), ('ALTOTONGA', 'ALTOTONGA, VER.'), ('JUCHIQUE', 'JUCHIQUE DE FERRER, VER.'), ('POZA_RICA', 'POZA RICA, VER.'), ('CUERNAVACA', 'CUERNAVACA, MOR.'), ('URUAPAN', 'URUAPAN, MICH.'), ('CARDENAS', 'CARDENAS, TAB.'), ('GUADALAJARA', 'GUADALAJARA, JAL.'), ('SILAO', 'SILAO, GTO.'), ('PACHUCA', 'PACHUCA, HGO.'), ('CANCUN', 'CANCÚN, Q. R.'), ('JUAREZ', 'CIUDAD JUÁREZ, CHIH.'), ('MATIAS_ROMERO', 'MATÍAS ROMERO, OAX.'), ('CHILPANCINGO', 'CHILPANCINGO, GRO.'), ('TIJUANA', 'TIJUANA, B.C.'), ('REYNOSA', 'REYNOSA, TAMPS.'), ('TOLUCA', 'TOLUCA, EDO. DE MEX.'), ('OAXACA', 'OAXACA, OAX.'), ('ELGIN', 'ELGIN ILLINOIS, EUA'), ('TAPACHULA', 'TAPACHULA, CHIS.'), ('CABO', 'CABO SAN LUCAS, B.C.S.'), ('TEZIUTLAN', 'TEZIUTLÁN, PUE.'), ('TAMPICO', 'TAMPICO, TAMPS.'), ('VERACRUZ', 'VERACRUZ, VER.'), ('TOPILEJO', 'TOPILEJO, CD. MEX.'), ('NEZA', 'CIUDAD NEZAHUALCÓYOTL, EDOMEX'), ('MIRAFLORES', 'MIRAFLORES, EDOMEX'), ('CALPULALPAN', 'CALPULALPAN, TLAX.'), ('COYOTEPEC', 'COYOTEPEC, EDOMEX'), ('CENTRO_SUR', 'CENTRO Y SUDAMÉRICA')], max_length=100, null=True),
        ),
    ]
