# Generated by Django 6.0 on 2026-01-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0005_asistencia_asistio_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='correo_electronico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
